import { User } from '@/entities/User';

const userData: Pick<
  User,
  'id' | 'firstName' | 'lastName' | 'email' | 'password'
>[] = [
  {
    id: 2,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: 'Password123',
  },
  {
    id: 3,
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane.doe@example.com',
    password: 'Password123',
  },
  {
    id: 4,
    firstName: 'Alice',
    lastName: 'Smith',
    email: 'alice.smith@example.com',
    password: 'Password123',
  },
  {
    id: 5,
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@example.com',
    password: 'Password123',
  },
  {
    id: 6,
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily.brown@example.com',
    password: 'Password123',
  },
  {
    id: 7,
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@example.com',
    password: 'Password123',
  },
  {
    id: 8,
    firstName: 'Jessica',
    lastName: 'Davis',
    email: 'jessica.davis@example.com',
    password: 'Password123',
  },
  {
    id: 9,
    firstName: 'Matthew',
    lastName: 'Miller',
    email: 'matthew.miller@example.com',
    password: 'Password123',
  },
  {
    id: 10,
    firstName: 'Sarah',
    lastName: 'Wilson',
    email: 'sarah.wilson@example.com',
    password: 'Password123',
  },
  {
    id: 11,
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez@example.com',
    password: 'Password123',
  },
  {
    id: 12,
    firstName: 'Jennifer',
    lastName: 'Anderson',
    email: 'jennifer.anderson@example.com',
    password: 'Password123',
  },
  {
    id: 13,
    firstName: 'Christopher',
    lastName: 'Taylor',
    email: 'christopher.taylor@example.com',
    password: 'Password123',
  },
  {
    id: 14,
    firstName: 'Amanda',
    lastName: 'Thomas',
    email: 'amanda.thomas@example.com',
    password: 'Password123',
  },
  {
    id: 15,
    firstName: 'Daniel',
    lastName: 'Hernandez',
    email: 'daniel.hernandez@example.com',
    password: 'Password123',
  },
  {
    id: 16,
    firstName: 'Melissa',
    lastName: 'Moore',
    email: 'melissa.moore@example.com',
    password: 'Password123',
  },
  {
    id: 17,
    firstName: 'James',
    lastName: 'Clark',
    email: 'james.clark@example.com',
    password: 'Password123',
  },
  {
    id: 18,
    firstName: 'Laura',
    lastName: 'Lewis',
    email: 'laura.lewis@example.com',
    password: 'Password123',
  },
  {
    id: 19,
    firstName: 'Kevin',
    lastName: 'Walker',
    email: 'kevin.walker@example.com',
    password: 'Password123',
  },
  {
    id: 20,
    firstName: 'Megan',
    lastName: 'Young',
    email: 'megan.young@example.com',
    password: 'Password123',
  },
  {
    id: 21,
    firstName: 'Tyler',
    lastName: 'Harris',
    email: 'tyler.harris@example.com',
    password: 'Password123',
  },
  {
    id: 22,
    firstName: 'Jordan',
    lastName: 'Lee',
    email: 'jordan.lee@example.com',
    password: 'Password123',
  },
  {
    id: 23,
    firstName: 'Alexis',
    lastName: 'Garcia',
    email: 'alexis.garcia@example.com',
    password: 'Password123',
  },
  {
    id: 24,
    firstName: 'Brandon',
    lastName: 'Young',
    email: 'brandon.young@example.com',
    password: 'Password123',
  },
  {
    id: 25,
    firstName: 'Rachel',
    lastName: 'Scott',
    email: 'rachel.scott@example.com',
    password: 'Password123',
  },
  {
    id: 26,
    firstName: 'Justin',
    lastName: 'Perez',
    email: 'justin.perez@example.com',
    password: 'Password123',
  },
  {
    id: 27,
    firstName: 'Hannah',
    lastName: 'King',
    email: 'hannah.king@example.com',
    password: 'Password123',
  },
  {
    id: 28,
    firstName: 'Andrew',
    lastName: 'Wright',
    email: 'andrew.wright@example.com',
    password: 'Password123',
  },
  {
    id: 29,
    firstName: 'Madison',
    lastName: 'Lopez',
    email: 'madison.lopez@example.com',
    password: 'Password123',
  },
  {
    id: 30,
    firstName: 'Cameron',
    lastName: 'Hill',
    email: 'cameron.hill@example.com',
    password: 'Password123',
  },
  {
    id: 31,
    firstName: 'Jordan',
    lastName: 'Baker',
    email: 'jordan.baker@example.com',
    password: 'Password123',
  },
];

export default userData;
